# -*- coding: utf-8 -*-
"""SHAPE_AI_PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15V7sH2Yks2VC7Cj08lIzsfFCZo8e_iu2
"""

import requests
#import os
from datetime import datetime

api_key = '87d845b0b6cf29baa1a73cc34b067a95'
location = input("Enter the city name: ")

complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

#create variables to store and display data
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

report = open('weather_report.txt', 'w')

report.write ("-------------------------------------------------------------")
report.write ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
report.write ("-------------------------------------------------------------")



report.write ("Current temperature is: {:.2f} deg C".format(temp_city))
report.write ("Description           :" + weather_desc)
report.write ("Humidity              :" + str(hmdt) + '%')
report.write ("Wind Speed            :" + str(wind_spd) + 'kmph')

report.close()

